### ISSUE TITLE
LocalReader Plugin Not Available in Store

### ISSUE THREAD

**Issue by josefdc** [Phate334/chatgpt-local-reader-plugin#1]
### Description
I've noticed that the localhost plugin, which is essential for the functionality of the `chatgpt-local-reader-plugin`, is currently not available in the store. This issue is preventing users from fully utilizing the capabilities of the `chatgpt-local-reader-plugin`.

### Steps to Reproduce
1. Navigate to the plugin store.
2. Search for the localhost plugin.

### Expected Behavior
The localhost plugin should be available for installation from the store.

### Actual Behavior
The localhost plugin is not found in the store.

### Possible Solution
Please consider adding the localhost plugin back to the store to ensure the `chatgpt-local-reader-plugin` can function as intended. 

Thank you for your attention to this matter.

**Comment by Phate334** [comment]
Hello @josefdc, I apologize for the misunderstanding. This plugin is an extension of the Python http.server module, enabling ChatGPT to directly read local directories. Therefore, it's not feasible to list it in the store.
